### ISSUE TITLE
Test and support Python 3

### ISSUE THREAD

**Issue by twolfson** [twolfson/sublime-info#4]
During development, we ran against Python 2.7 only. I am fairly certain we are cross-version compatible but we should enable Python 3.3 in Travis just to be certain.

**Comment by adambullmer** [comment]
Doesn't work on python 3.4

```import sublime_info
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f137ea1814a5> in <module>()
----> 1 import sublime_info

sublime-info/sublime_info/__init__.py in <module>()
      1 # Load in local modules for extension
----> 2 from sublime_info import SublimeInfo
      3 from errors import *
      4 
      5 # Define sugar methods

ImportError: cannot import name 'SublimeInfo'
```

after resolving the above error by using absolute imports, I am getting:

```
sublime-info/sublime_info/SublimeInfo.py in <module>()
      3 import re
      4 import subprocess
----> 5 from shutilwhich import which
      6 from errors import STNotResolvedError, STBadLocationError
      7 

ImportError: cannot import name 'which'
```

Probably ought to wrap the imports with a try/except for backwards compatibility

```py
try:
  from shutil import which
except ImportError:
  from shutilwhich import which
```

**Comment by twolfson** [comment]
Would you be interested in opening a PR to fix up the one-offs?

**Comment by twolfson** [comment]
This has been resolved via @adambullmer's work in #5 and released in `0.2.0` :tada:

**Comment by adambullmer** [comment]
I think your `sublime_harness` needs an update to to it's requirements.txt to bump the version of it's dependency of this repo

**Comment by twolfson** [comment]
Ah, yea. There's probably a cascade of changes to be done in the Sublime Text tests framework. I'm not sure how much time I want to invest in that since it's mostly dusty and I wasn't too satisfied with the workflow =/

Are you looking at using that?

**Comment by adambullmer** [comment]
Yeah, That's how I landed on this bug. Fortunately, at my package level I can override dependency versions. I'm testing now to see if there are any other issues with it. Might join you on jumping ship if this proves too difficult.

**Comment by twolfson** [comment]
Yea, if it is actually working, then I will be surprised. I remember it being rage inducing by the time I finished my work.

randy3k wrote another package and took notes on the alternatives:

https://github.com/randy3k/UnitTesting

In any case, let me know what happens =). If it's effed, then I should be responsible and put up deprecation notices.

**Comment by adambullmer** [comment]
So as far as I can tell, the harness works. However, I'm trying to run this through tox and it seems like a file isn't being written where we expect it to, so the test never completes. This is happening on the `harness.run()` command. If you've got any lead given this issue, I'd be more than happy to dive a little deeper. Otherwise I think I've explored all I can on this project.

**Comment by twolfson** [comment]
Yea, I am not looking forward to debugging that mess -- it was choc full of race conditions and debugging visual components in a non-visual environment. Prob going to deprecate it =(

**Comment by twolfson** [comment]
Sorry for the slow follow up on this. Before I deprecate `sublime-plugin-tests`, I want to explore to rest of the landscape (still not too familiar with randy3k's version). I will take a look at everything by the end of next weekend.

**Comment by twolfson** [comment]
Finally got around to exploring `UnitTesting`. I think it has enough overlap with `sublime-plugin-tests` and is much further along (e.g. OS X and Windows support) that we can deprecate:

https://github.com/twolfson/sublime-plugin-tests

https://github.com/twolfson/sublime-plugin-tests-base

https://github.com/twolfson/sublime-harness

**Comment by twolfson** [comment]
Alright, I have posted a deprecation notice on each of the repos. Thanks for the push to close out this issue on this repo though =)
